-- Librería de 85 nudges conductuales en 16 categorías.
-- Consumida por el Behavioral Science Optimizer (skill 2).

BEGIN;

CREATE TABLE IF NOT EXISTS behavioral_nudges (
  id                     SERIAL PRIMARY KEY,
  nudge_id               VARCHAR(80) UNIQUE NOT NULL,
  nudge_name             VARCHAR(150) NOT NULL,
  category               VARCHAR(40) NOT NULL,
  subcategory            VARCHAR(60),
  description            TEXT NOT NULL,
  example_generic        TEXT,
  example_education      TEXT,
  example_b2b            TEXT,
  best_for               TEXT,
  avoid_when             TEXT,
  combines_well_with     JSONB NOT NULL DEFAULT '[]'::jsonb,
  intensity              VARCHAR(10) NOT NULL CHECK (intensity IN ('low','medium','high')),
  ethical_consideration  TEXT,
  is_active              BOOLEAN NOT NULL DEFAULT TRUE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_nudges_category ON behavioral_nudges(category) WHERE is_active;

INSERT INTO behavioral_nudges
  (nudge_id, nudge_name, category, subcategory, description, example_generic, example_education, example_b2b, best_for, avoid_when, combines_well_with, intensity, ethical_consideration)
VALUES
-- =============== SCARCITY (8) ===============
('SCARCITY_LIMITED_QUANTITY','Limited Quantity','SCARCITY','Quantity',
 'Destaca un tope fijo y bajo de unidades/plazas para disparar FOMO.',
 'Solo 50 asientos.','Solo 30 becas para cohorte 2026.','Solo 10 licencias enterprise este trimestre.',
 'Cuando el inventario es realmente limitado y el ticket es alto.',
 'Cuando la oferta es ilimitada — suena manipulador.',
 '["SCARCITY_STOCK_COUNTDOWN","URGENCY_DEADLINE_COUNTDOWN","LOSS_AVERSION_MISSING_OUT"]'::jsonb,
 'high','Falsa escasez erosiona confianza; solo con tope real.'),

('SCARCITY_LIMITED_TIME','Limited Time','SCARCITY','Time',
 'Ventana temporal corta para completar la acción.',
 'Oferta por 48 horas.','Inscripciones cierran el viernes.','Promo Black Friday hasta la medianoche.',
 'Descuentos, lanzamientos, fechas claras.',
 'Cuando la promo se repite siempre — pierde efecto.',
 '["URGENCY_DEADLINE_COUNTDOWN","SCARCITY_LIMITED_QUANTITY","LOSS_AVERSION_MISSING_OUT"]'::jsonb,
 'high','No extender deadlines artificialmente; daña credibilidad.'),

('SCARCITY_SEASONAL','Seasonal Scarcity','SCARCITY','Time',
 'Disponibilidad atada a estación o período del año.',
 'Edición verano, no se repite.','Curso solo en cohorte marzo.','Pricing fiscal-year hasta junio.',
 'Productos estacionales o cohortes académicas.',
 'Productos evergreen sin ciclo real.',
 '["FRESHSTART_NEW_SEMESTER","SCARCITY_LIMITED_TIME"]'::jsonb,
 'medium','Debe coincidir con ciclo real de producto/mercado.'),

('SCARCITY_GEOGRAPHIC','Geographic Scarcity','SCARCITY','Location',
 'Beneficio exclusivo para una región/ciudad.',
 'Solo en CDMX.','Programa presencial exclusivo Buenos Aires.','Soporte 24/7 solo en Latam norte.',
 'Go-to-market regional o piloto geográfico.',
 'Producto digital 100% global sin diferenciación.',
 '["SCARCITY_EXCLUSIVE_ACCESS","STATUS_EXCLUSIVITY"]'::jsonb,
 'medium','No usar para excluir ilegalmente.'),

('SCARCITY_EXCLUSIVE_ACCESS','Exclusive Access','SCARCITY','Access',
 'Acceso reservado a un grupo privilegiado.',
 'Acceso anticipado para miembros.','Beta cerrada para alumnos activos.','Tier enterprise con datos privados.',
 'Programas de fidelidad o cuentas premium.',
 'Cuando cualquiera puede unirse sin fricción.',
 '["STATUS_VIP_TREATMENT","STATUS_ELITE_GROUP","SOCIAL_PROOF_COMPANY_LOGOS"]'::jsonb,
 'high','No prometer exclusividad que no se cumple.'),

('SCARCITY_WAITLIST','Waitlist Pressure','SCARCITY','Access',
 'Señalar lista de espera para dramatizar demanda.',
 '5.000 en lista esperando cupo.','Lista de espera abierta para cohorte 2026.','Waitlist priority para enterprise.',
 'Lanzamientos y pre-seed demand.',
 'Si no hay realmente cola — mentira verificable.',
 '["SOCIAL_PROOF_USER_NUMBERS","SCARCITY_LIMITED_QUANTITY"]'::jsonb,
 'medium','Comunicar siempre cifras reales.'),

('SCARCITY_STOCK_COUNTDOWN','Stock Countdown','SCARCITY','Quantity',
 'Contador visible de unidades remanentes que baja.',
 'Quedan 3 unidades.','2 cupos libres en la cohorte.','1 licencia disponible a este precio.',
 'E-commerce, SaaS con tier caps.',
 'Productos con stock ilimitado o infinito.',
 '["SCARCITY_LIMITED_QUANTITY","URGENCY_DEADLINE_COUNTDOWN"]'::jsonb,
 'high','No simular contadores falsos — fraude comercial.'),

('SCARCITY_ENROLLMENT_WINDOWS','Enrollment Windows','SCARCITY','Time',
 'Períodos discretos para inscripción con cierre duro.',
 'Inscripciones abren solo 72 h.','Matrícula cada 3 meses.','Onboarding window cierra viernes.',
 'Bootcamps, programas cohortizados.',
 'Cuando el producto es evergreen sin batches.',
 '["SCARCITY_LIMITED_TIME","FRESHSTART_NEW_SEMESTER"]'::jsonb,
 'medium','Respetar cierre real; no re-abrir discrecionalmente.'),

-- =============== SOCIAL PROOF (10) ===============
('SOCIAL_PROOF_SUCCESS_RATE','Success Rate','SOCIAL_PROOF','Statistical',
 'Porcentaje de éxito obtenido por usuarios previos.',
 '94% de satisfacción.','87% de egresados consigue trabajo en 6 meses.','92% de clientes renueva anualmente.',
 'Casos con data defendible.',
 'Sin métrica real o con muestra chica.',
 '["AUTHORITY_RESEARCH_BACKED","SOCIAL_PROOF_USER_NUMBERS"]'::jsonb,
 'high','Definir numerador/denominador; evitar cherry-picking.'),

('SOCIAL_PROOF_USER_NUMBERS','User Numbers','SOCIAL_PROOF','Aggregate',
 'Tamaño de la base instalada o comunidad.',
 'Más de 100.000 usuarios.','+50.000 alumnos activos.','Usado por más de 2.000 empresas.',
 'Comunidades grandes consolidadas.',
 'Productos nuevos con base chica.',
 '["SOCIAL_PROOF_COMPANY_LOGOS","SOCIAL_PROOF_WISDOM_OF_CROWDS"]'::jsonb,
 'medium','Cifras auditables; evitar inflar.'),

('SOCIAL_PROOF_EXPERT_ENDORSEMENT','Expert Endorsement','SOCIAL_PROOF','Authority-based',
 'Respaldo explícito de un experto reconocido.',
 'Recomendado por el Dr. X.','Avalado por la Sociedad Argentina de Pediatría.','Partner certificado por AWS.',
 'Productos técnicos o de salud.',
 'Si el experto no tiene reputación real en el vertical.',
 '["AUTHORITY_CERTIFICATION","AUTHORITY_ACADEMIC_CREDENTIALS"]'::jsonb,
 'high','Pagar por endorsement debe declararse.'),

('SOCIAL_PROOF_PEER_TESTIMONIALS','Peer Testimonials','SOCIAL_PROOF','Testimonial',
 'Testimonios de usuarios similares al target.',
 '"Cambió mi rutina" — Laura, 34.','"Cambié de carrera gracias a esto" — Matías, egresado 2024.','"Redujimos churn 30%" — CFO Acme.',
 'Cuando el target se identifica con el persona citado.',
 'Testimonios falsos o genéricos sin rostro.',
 '["LIKING_SIMILARITY","SOCIAL_PROOF_BEFORE_AFTER"]'::jsonb,
 'medium','Consentimiento escrito del citado.'),

('SOCIAL_PROOF_RATING_REVIEWS','Rating / Reviews','SOCIAL_PROOF','Aggregate',
 'Valoración agregada visible (estrellas, %).',
 '4.8/5 con 2.100 reviews.','Puntaje 9.2 en plataforma de cursos.','Capterra 4.7/5.',
 'Productos con tracción comprobable.',
 'Pocas reviews — cualquier negativa pesa demasiado.',
 '["SOCIAL_PROOF_USER_NUMBERS","AUTHORITY_AWARDS"]'::jsonb,
 'medium','No borrar reviews negativas selectivamente.'),

('SOCIAL_PROOF_MEDIA_MENTIONS','Media Mentions','SOCIAL_PROOF','Authority-based',
 'Citas o coverage en medios relevantes.',
 'Visto en Forbes.','Cubierto por La Nación Educación.','Caso destacado en Harvard Business Review.',
 'B2B y premium, cuando los medios son top-tier.',
 'Medios irrelevantes para el target.',
 '["AUTHORITY_AWARDS","SOCIAL_PROOF_EXPERT_ENDORSEMENT"]'::jsonb,
 'medium','Citar fielmente; no distorsionar quote.'),

('SOCIAL_PROOF_COMPANY_LOGOS','Company Logos','SOCIAL_PROOF','Aggregate',
 'Logos de clientes reconocidos ("as seen by…").',
 '','Universidad X ya lo usa.','Usado por Google, Mercado Libre, Rappi.',
 'B2B enterprise, SaaS, consultoría.',
 'Para B2C puro — irrelevante.',
 '["SOCIAL_PROOF_USER_NUMBERS","AUTHORITY_OFFICIAL_PARTNERSHIP"]'::jsonb,
 'high','Autorización escrita para usar logos.'),

('SOCIAL_PROOF_BEFORE_AFTER','Before/After Stories','SOCIAL_PROOF','Testimonial',
 'Historia con transformación tangible.',
 'De 0 a 10K seguidores en 60 días.','De no encontrar empleo a CTO en 18 meses.','De 4h/semana de reporting a 10min.',
 'Productos con outcome medible.',
 'Resultados atípicos sin disclaimer.',
 '["SALIENCE_CONCRETE_NUMBERS","SOCIAL_PROOF_PEER_TESTIMONIALS"]'::jsonb,
 'high','Incluir disclaimer "resultados no garantizados".'),

('SOCIAL_PROOF_WISDOM_OF_CROWDS','Wisdom of Crowds','SOCIAL_PROOF','Aggregate',
 'Indicar que "la mayoría" elige cierta opción.',
 'La opción más elegida.','Plan elegido por el 70% de estudiantes.','Pricing más contratado por startups Series A.',
 'Menús de opciones con un "default social".',
 'Cuando lleva al usuario a opción no óptima para él.',
 '["DEFAULTS_PRE_SELECTION","FRAMING_ANCHORING_HIGH"]'::jsonb,
 'medium','No forzar elección subóptima para el usuario.'),

('SOCIAL_PROOF_CELEBRITY_INFLUENCER','Celebrity / Influencer','SOCIAL_PROOF','Authority-based',
 'Asociación con figura pública aspiracional.',
 'Usado por Messi.','Recomendado por Coscu.','Respaldado por Patty Azcárate.',
 'Consumo masivo, lifestyle.',
 'B2B técnico o cuando la celebridad no encaja con marca.',
 '["STATUS_ASPIRATION_MODELING","LIKING_SIMILARITY"]'::jsonb,
 'medium','Declarar relación comercial (#ad).'),

-- =============== LOSS AVERSION (7) ===============
('LOSS_AVERSION_OPPORTUNITY_COST','Opportunity Cost','LOSS_AVERSION','Opportunity',
 'Poner en valor lo que se deja de ganar al no actuar.',
 'Cada día sin X, perdés Y.','Cada mes sin capacitarte, perdés $X de salario futuro.','Cada trimestre sin automatizar: 200 h de equipo.',
 'Decisiones con costo ambiguo invisible.',
 'Cuando no hay data plausible para el número.',
 '["URGENCY_IMMEDIATE_BENEFIT","LOSS_AVERSION_MISSING_OUT"]'::jsonb,
 'high','No inflar el costo para manipular.'),

('LOSS_AVERSION_COMPETITOR_ADVANTAGE','Competitor Advantage','LOSS_AVERSION','Status-quo',
 'Mostrar que la competencia gana terreno mientras el target duda.',
 'Tu competencia ya lo hace.','Compañeros de tu carrera ya lo tienen.','7 de cada 10 competidores ya migraron.',
 'B2B competitivo, mercados maduros.',
 'Si la ventaja del competidor no es real o verificable.',
 '["SOCIAL_PROOF_USER_NUMBERS","URGENCY_FIRST_MOVER_ADVANTAGE"]'::jsonb,
 'high','No fabricar ventajas ajenas.'),

('LOSS_AVERSION_CAREER_STAGNATION','Career Stagnation','LOSS_AVERSION','Opportunity',
 'Pintar el costo de no crecer profesionalmente.',
 '','Quedarte en el mismo puesto 3 años te descontextualiza.','Sin upskilling tu equipo, la brecha se amplía.',
 'Educación ejecutiva, corporate training.',
 'Si induce ansiedad sin ofrecer solución clara.',
 '["LOSS_AVERSION_OPPORTUNITY_COST","FRESHSTART_LIFE_MILESTONE"]'::jsonb,
 'high','Balancear con narrativa aspiracional.'),

('LOSS_AVERSION_SUNK_COST','Sunk Cost','LOSS_AVERSION','Status-quo',
 'Reencuadrar el esfuerzo ya invertido para evitar "tirarlo".',
 '','Ya llevás 2 años de carrera — no te frenes ahora.','Ya invertiste $X en tooling — capitalizalo.',
 'Renovaciones, extensiones, siguientes etapas.',
 'Cuando el "sunk" realmente no justifica seguir.',
 '["COMMITMENT_PROGRESS_TRACKING","COMMITMENT_IDENTITY_ALIGNMENT"]'::jsonb,
 'medium','Eticamente discutible; no usar para atrapar.'),

('LOSS_AVERSION_REGRET_MINIMIZATION','Regret Minimization','LOSS_AVERSION','Regret-based',
 'Proyectar el target a futuro: ¿te vas a arrepentir?',
 'No pases el verano arrepintiéndote.','En 5 años, ¿vas a lamentar no haber aplicado?','¿Vas a mirar atrás deseando haber migrado antes?',
 'Decisiones de gran impacto, one-shot.',
 'Decisiones triviales — suena desproporcionado.',
 '["FRESHSTART_LIFE_MILESTONE","SALIENCE_VIVID_EXAMPLES"]'::jsonb,
 'high','Cuidar tono; no inducir ansiedad gratuita.'),

('LOSS_AVERSION_MISSING_OUT','Missing Out (FOMO)','LOSS_AVERSION','Opportunity',
 'Señalar que otros ya aprovechan mientras el target duda.',
 'Otros ya están disfrutándolo.','Cohorte 2024 ya consiguió trabajo; vos aún no empezaste.','Competencia ya implementó; vos seguís evaluando.',
 'Redes sociales, lanzamientos virales.',
 'B2B de ciclo largo — pierde potencia.',
 '["SOCIAL_PROOF_USER_NUMBERS","URGENCY_DEADLINE_COUNTDOWN"]'::jsonb,
 'high','Límite ético — no explotar ansiedad social.'),

('LOSS_AVERSION_STATUS_QUO_RISK','Status Quo Risk','LOSS_AVERSION','Status-quo',
 'Reencuadrar no-actuar como la opción riesgosa.',
 'No cambiar también es una decisión.','Quedarte en la misma carrera también tiene costo.','No migrar la infra es apostar a que nada cambia.',
 'Ventas complejas donde la inercia gana.',
 'Cuando el cambio propuesto es realmente riesgoso.',
 '["LOSS_AVERSION_COMPETITOR_ADVANTAGE","URGENCY_MARKET_SHIFT"]'::jsonb,
 'medium','Honestidad sobre el riesgo real del cambio.'),

-- =============== URGENCY (6) ===============
('URGENCY_DEADLINE_COUNTDOWN','Deadline Countdown','URGENCY','Deadline',
 'Cuenta regresiva visible hasta cierre.',
 'Cierra en 23:59:12.','Inscripción cierra en 48h.','Early-bird pricing termina hoy 23:59.',
 'Campañas de conversión, promos concretas.',
 'Si el deadline se extiende siempre — pierde credibilidad.',
 '["SCARCITY_LIMITED_TIME","LOSS_AVERSION_MISSING_OUT"]'::jsonb,
 'high','Respetar cierre real; no hacer fake timers.'),

('URGENCY_PRICE_INCREASE_ALERT','Price Increase Alert','URGENCY','Deadline',
 'Avisar suba de precio en fecha próxima.',
 'Precio sube +15% el lunes.','Matrícula +20% desde mayo.','Nuevo pricing Q3 — asegurá el tuyo.',
 'Planes con tiers de precio escalonados.',
 'Si el precio nunca sube — erosiona trust.',
 '["FRAMING_ANCHORING_HIGH","URGENCY_DEADLINE_COUNTDOWN"]'::jsonb,
 'high','Cumplir efectivamente la suba anunciada.'),

('URGENCY_IMMEDIATE_BENEFIT','Immediate Benefit','URGENCY','Event-driven',
 'Enfatizar que el valor se percibe hoy, no mañana.',
 'Hoy mismo empezás a ver resultados.','Comenzás a aprender hoy.','Empezás a ahorrar horas desde mañana.',
 'Productos con quick win verificable.',
 'Productos cuya curva de valor es larga (meses).',
 '["PRESENT_BIAS_INSTANT_GRATIFICATION","PRESENT_BIAS_QUICK_WIN"]'::jsonb,
 'medium','No prometer resultado inmediato irreal.'),

('URGENCY_BREAKING_NEWS','Breaking News','URGENCY','Event-driven',
 'Atar la acción a un evento actual relevante.',
 'Con la suba del dólar, ahorrá comprando hoy.','Nueva ley educativa — prepárate antes que el resto.','Cambio regulatorio — adaptá tu operación en 30 días.',
 'Coyuntura macro, regulatoria.',
 'Eventos irrelevantes al producto.',
 '["URGENCY_MARKET_SHIFT","FRESHSTART_MARKET_SHIFT"]'::jsonb,
 'medium','No aprovechar tragedias o crisis sociales.'),

('URGENCY_MARKET_SHIFT','Market Shift','URGENCY','Market-driven',
 'Enmarcar cambio de mercado que exige acción.',
 'El mercado cambió — adaptate.','La demanda laboral se movió a AI.','El CAC subió 40% YoY — optimizá tu funnel.',
 'B2B transformación digital, carreras.',
 'Cambios ya viejos o genéricos.',
 '["LOSS_AVERSION_STATUS_QUO_RISK","URGENCY_FIRST_MOVER_ADVANTAGE"]'::jsonb,
 'medium','Datos verificables del shift.'),

('URGENCY_FIRST_MOVER_ADVANTAGE','First Mover Advantage','URGENCY','Market-driven',
 'Posicionar al target como el pionero que captura valor.',
 'Sé el primero en tu círculo.','Primer graduado de tu universidad en el programa.','Primeros early adopters capturan precio 2024.',
 'Mercados emergentes, tecnologías nuevas.',
 'Mercados saturados — ya no es primer.',
 '["STATUS_ELITE_GROUP","SCARCITY_EXCLUSIVE_ACCESS"]'::jsonb,
 'medium','No exagerar ventaja competitiva.'),

-- =============== AUTHORITY (7) ===============
('AUTHORITY_CERTIFICATION','Certification','AUTHORITY','Credentials',
 'Mostrar certificaciones oficiales que validan el producto/persona.',
 'Certificación ISO 9001.','Certificación oficial del Ministerio.','SOC 2 Type II certified.',
 'Sectores regulados, enterprise.',
 'Certificaciones irrelevantes o vencidas.',
 '["AUTHORITY_OFFICIAL_PARTNERSHIP","AUTHORITY_GOVERNMENT_RECOGNITION"]'::jsonb,
 'high','Cita el cert ID verificable.'),

('AUTHORITY_YEARS_EXPERIENCE','Years of Experience','AUTHORITY','Experience',
 'Antigüedad del equipo/marca como prueba de track record.',
 '25 años en el rubro.','Docentes con 15+ años de práctica.','Consultores ex-McKinsey 20 años.',
 'Consultoría, educación premium, servicios pro.',
 'Startups cuyo valor es la innovación, no la tradición.',
 '["SOCIAL_PROOF_EXPERT_ENDORSEMENT","AUTHORITY_ACADEMIC_CREDENTIALS"]'::jsonb,
 'medium','Años reales; equipos nuevos no inflar.'),

('AUTHORITY_ACADEMIC_CREDENTIALS','Academic Credentials','AUTHORITY','Credentials',
 'Instituciones académicas top respaldan el contenido.',
 'Basado en Harvard Business School.','Programa avalado por Universidad Austral.','Metodología validada en MIT.',
 'Productos educativos premium, consulting.',
 'Mass market sin credibilidad académica real.',
 '["AUTHORITY_CERTIFICATION","AUTHORITY_RESEARCH_BACKED"]'::jsonb,
 'high','Verificable; no licencias mal citadas.'),

('AUTHORITY_OFFICIAL_PARTNERSHIP','Official Partnership','AUTHORITY','Recognition',
 'Partnership formal con marca reconocida.',
 'Partner oficial de Nike.','Convenio con Universidad X.','AWS Advanced Partner.',
 'Ecosistemas tech, educación formal.',
 'Partnerships lazy que no agregan credibilidad.',
 '["SOCIAL_PROOF_COMPANY_LOGOS","AUTHORITY_CERTIFICATION"]'::jsonb,
 'high','Partnership real, no rebranding.'),

('AUTHORITY_AWARDS','Awards','AUTHORITY','Recognition',
 'Premios o reconocimientos relevantes.',
 'Ganador del Effie 2024.','Premio educativo Sadosky.','Forbes 30u30 del CEO.',
 'Marcas con trayectoria premiable.',
 'Premios oscuros o comprados.',
 '["SOCIAL_PROOF_MEDIA_MENTIONS","AUTHORITY_OFFICIAL_PARTNERSHIP"]'::jsonb,
 'medium','Mencionar año y categoría específica.'),

('AUTHORITY_RESEARCH_BACKED','Research-Backed','AUTHORITY','Credentials',
 'Producto con evidencia científica publicada.',
 'Basado en estudio con 5.000 sujetos.','Pedagogía validada en 3 papers.','Modelo entrenado sobre dataset de 10M.',
 'Salud, educación, productos técnicos.',
 'Research débil o cherry-picked.',
 '["AUTHORITY_ACADEMIC_CREDENTIALS","SOCIAL_PROOF_SUCCESS_RATE"]'::jsonb,
 'high','Citar fuente verificable (DOI/link).'),

('AUTHORITY_GOVERNMENT_RECOGNITION','Government Recognition','AUTHORITY','Recognition',
 'Aprobación de organismo público.',
 'Aprobado por ANMAT.','Título oficial del Ministerio de Educación.','Registrado en el INTI.',
 'Salud, educación, finanzas.',
 'Cuando no hay reconocimiento real.',
 '["AUTHORITY_CERTIFICATION","AUTHORITY_OFFICIAL_PARTNERSHIP"]'::jsonb,
 'high','Solo si está efectivamente aprobado.'),

-- =============== RECIPROCITY (5) ===============
('RECIPROCITY_FREE_TRIAL','Free Trial','RECIPROCITY','Free-offer',
 'Permitir usar el producto sin pagar por un período.',
 '30 días gratis.','Primera clase gratis.','14 días sin tarjeta.',
 'SaaS, servicios, suscripciones.',
 'Productos físicos sin return-ready logistics.',
 '["COMMITMENT_SMALL_FIRST_STEP","DEFAULTS_ONE_CLICK"]'::jsonb,
 'medium','Ser claro sobre qué pasa al terminar el trial.'),

('RECIPROCITY_FREE_RESOURCES','Free Resources','RECIPROCITY','Free-offer',
 'Ebooks, guías, templates gratuitos.',
 'Descargá la guía gratis.','Plantilla de CV descargable.','Benchmark 2026 gratuito.',
 'Lead-gen top-of-funnel.',
 'Cuando el recurso es pobre — daña reputación.',
 '["COMMITMENT_SMALL_FIRST_STEP","CURIOSITY_KNOWLEDGE_GAP"]'::jsonb,
 'low','Que el recurso sea realmente útil, no clickbait.'),

('RECIPROCITY_FREE_ASSESSMENT','Free Assessment','RECIPROCITY','Free-offer',
 'Diagnóstico o evaluación sin costo.',
 'Test gratuito de perfil.','Evaluación vocacional gratis.','Auditoría de infra gratis.',
 'Ventas consultivas B2B y B2C premium.',
 'Productos bajo ticket — no escala.',
 '["SOCIAL_PROOF_EXPERT_ENDORSEMENT","COMMITMENT_SMALL_FIRST_STEP"]'::jsonb,
 'medium','Que el assessment tenga valor real standalone.'),

('RECIPROCITY_BONUS_CONTENT','Bonus Content','RECIPROCITY','Free-offer',
 'Valor agregado inesperado al comprar/registrarse.',
 'Sumá un capítulo extra.','Bonus masterclass gratis al inscribirte.','Extra onboarding call incluido.',
 'Cuando el bonus es aspiracional y relevante.',
 'Bonus irrelevante — se siente relleno.',
 '["FRAMING_GAIN_FRAME","COMMITMENT_PUBLIC_COMMITMENT"]'::jsonb,
 'low','No reempaquetar lo mismo como bonus.'),

('RECIPROCITY_MONEY_BACK','Money-Back Guarantee','RECIPROCITY','Risk-reversal',
 'Garantía de devolución si no satisface.',
 'Devolución total en 30 días.','Si no conseguís trabajo en 6 meses, reembolso.','ROI en 90 días o devolvemos la implementación.',
 'Productos premium o first-time buyers.',
 'Si el proceso de reembolso es oscuro.',
 '["LOSS_AVERSION_REGRET_MINIMIZATION","AUTHORITY_CERTIFICATION"]'::jsonb,
 'high','Cumplir reembolsos sin fricción extra.'),

-- =============== COMMITMENT & CONSISTENCY (5) ===============
('COMMITMENT_SMALL_FIRST_STEP','Small First Step','COMMITMENT_CONSISTENCY','Gradual-escalation',
 'Pedir un micro-compromiso inicial fácil.',
 'Solo 2 minutos.','Hacé un mini-test.','Descargá el primer template.',
 'Top-of-funnel, educación digital.',
 'Si el "paso grande" después es desproporcionado.',
 '["RECIPROCITY_FREE_RESOURCES","RECIPROCITY_FREE_TRIAL"]'::jsonb,
 'low','Transparencia sobre próximos pasos.'),

('COMMITMENT_PUBLIC_COMMITMENT','Public Commitment','COMMITMENT_CONSISTENCY','Identity-based',
 'Invitar a declarar el compromiso públicamente.',
 'Compartí tu objetivo.','Postealo en tu perfil.','Anunciá a tu equipo tu roadmap de tooling.',
 'Comunidades activas, redes.',
 'Culturas donde el fracaso público estigmatiza.',
 '["LIKING_SHARED_VALUES","COMMITMENT_IDENTITY_ALIGNMENT"]'::jsonb,
 'medium','No presionar compromiso público si es ansiógeno.'),

('COMMITMENT_PROGRESS_TRACKING','Progress Tracking','COMMITMENT_CONSISTENCY','Gradual-escalation',
 'Mostrar avance del usuario para sostener motivación.',
 '60% completado.','Llevás 12 de 40 clases.','Llevás 8 workflows migrados.',
 'Productos con journey extenso.',
 'Productos one-shot sin continuidad.',
 '["COMMITMENT_STREAK_MAINTENANCE","SALIENCE_CONCRETE_NUMBERS"]'::jsonb,
 'medium','Métrica honesta, no vanity.'),

('COMMITMENT_STREAK_MAINTENANCE','Streak Maintenance','COMMITMENT_CONSISTENCY','Gradual-escalation',
 'Incentivar racha (Duolingo-style).',
 'Tu racha: 15 días.','23 días estudiando — no lo rompas.','14 días sprint sin bugs críticos.',
 'Apps de uso diario, habit-building.',
 'Productos de uso esporádico.',
 '["COMMITMENT_PROGRESS_TRACKING","PRESENT_BIAS_INSTANT_GRATIFICATION"]'::jsonb,
 'high','No generar ansiedad de perder racha.'),

('COMMITMENT_IDENTITY_ALIGNMENT','Identity Alignment','COMMITMENT_CONSISTENCY','Identity-based',
 'Asociar el producto con la identidad aspiracional.',
 'Sos de los que no se conforman.','Vos sos alumno crítico, no de memoria.','Sos el tipo de líder que invierte en su gente.',
 'Lifestyle, educación ejecutiva.',
 'Cuando la identidad asignada es presumida.',
 '["STATUS_ASPIRATION_MODELING","LIKING_SHARED_VALUES"]'::jsonb,
 'medium','No imponer identidad falsa.'),

-- =============== LIKING (4) ===============
('LIKING_SIMILARITY','Similarity','LIKING','Similarity',
 'Subrayar "somos como vos" — background, problema.',
 'Te entendemos: también estuvimos ahí.','Fundado por ex-alumnos que querían otra cosa.','Equipo ex-CTOs que sufrieron la misma migración.',
 'Cuando la marca tiene rostro creíble.',
 'Marcas corporativas sin storytelling humano.',
 '["LIKING_ORIGIN_STORY","SOCIAL_PROOF_PEER_TESTIMONIALS"]'::jsonb,
 'medium','Ser honesto sobre el vínculo.'),

('LIKING_COMMON_ENEMY','Common Enemy','LIKING','Values-based',
 'Identificar un adversario compartido (no persona).',
 'Contra los clichés del rubro.','Contra el cramming inútil.','Contra los meetings eternos.',
 'Narrativas de ruptura.',
 'Crear enemigos falsos o personas reales.',
 '["LIKING_SHARED_VALUES","COMMITMENT_IDENTITY_ALIGNMENT"]'::jsonb,
 'medium','Nunca personal ni grupos vulnerables.'),

('LIKING_SHARED_VALUES','Shared Values','LIKING','Values-based',
 'Declarar valores explícitos coincidentes con target.',
 'Creemos en la simpleza radical.','Creemos en el pensamiento crítico.','Creemos en reducir meetings — no agregarlos.',
 'Productos con manifiesto.',
 'Valores performativos vacíos.',
 '["LIKING_COMMON_ENEMY","COMMITMENT_IDENTITY_ALIGNMENT"]'::jsonb,
 'low','Coherencia valor ↔ operación.'),

('LIKING_ORIGIN_STORY','Origin Story','LIKING','Similarity',
 'Contar cómo y por qué nació el producto.',
 'Lo creamos porque no encontrábamos nada así.','Empezó en un aula, no en un board.','Nació en una sala de on-call a las 3 am.',
 'Productos con fundador visible.',
 'Historias prefabricadas.',
 '["LIKING_SIMILARITY","LIKING_SHARED_VALUES"]'::jsonb,
 'low','Que sea la historia real, no ficción.'),

-- =============== FRAMING (6) ===============
('FRAMING_GAIN_FRAME','Gain Frame','FRAMING','Gain-loss',
 'Comunicar el beneficio en términos positivos.',
 'Ganá 2 horas al día.','Mejorá tu promedio 1.5 puntos.','Recuperá 8h/semana de tu equipo.',
 'Targets confiados y optimistas.',
 'Cuando la pérdida es más tangible que la ganancia.',
 '["SALIENCE_CONCRETE_NUMBERS","PRESENT_BIAS_QUICK_WIN"]'::jsonb,
 'medium','No inflar la ganancia.'),

('FRAMING_LOSS_FRAME','Loss Frame','FRAMING','Gain-loss',
 'Comunicar qué se pierde al no actuar.',
 'Cada día sin X, perdés Y.','Sin preparación perdés el ingreso.','Sin automatizar, quemás capital humano.',
 'Productos preventivos, seguros, salud.',
 'Top-of-funnel casual — parece alarmista.',
 '["LOSS_AVERSION_OPPORTUNITY_COST","LOSS_AVERSION_MISSING_OUT"]'::jsonb,
 'high','Equilibrar con camino claro de solución.'),

('FRAMING_POSITIVE_REFRAME','Positive Reframe','FRAMING','Reference-point',
 'Reencuadrar objeción como ventaja.',
 'No es caro, es una inversión.','No es difícil, es desafiante.','No es lento, es diligente.',
 'Cuando hay objeción clara identificada.',
 'Si la objeción es real y válida (engaño).',
 '["FRAMING_RELATIVE_COMPARISON","FRAMING_ANCHORING_HIGH"]'::jsonb,
 'low','Sin deshonestidad; la sustancia debe cumplir.'),

('FRAMING_ANCHORING_HIGH','Anchoring High','FRAMING','Reference-point',
 'Mostrar primero un precio/valor alto para anclar.',
 'Antes $1.000, ahora $499.','Consultoría privada $5k/h; programa $99/mes.','Enterprise $30k/año; startup $3k/año.',
 'Pricing, comparativas.',
 'Anclaje absurdo — no creíble.',
 '["FRAMING_RELATIVE_COMPARISON","URGENCY_PRICE_INCREASE_ALERT"]'::jsonb,
 'high','Si el precio "antes" es ficticio, es engaño.'),

('FRAMING_RELATIVE_COMPARISON','Relative Comparison','FRAMING','Reference-point',
 'Comparar el costo con algo cotidiano.',
 'Menos que un café por día.','Menos que tu delivery semanal.','Menos que una licencia de Excel por usuario.',
 'Pricing bajo ticket, recurring.',
 'Ticket alto — la comparación suena trucho.',
 '["SALIENCE_CONCRETE_NUMBERS","FRAMING_UNIT_BIAS"]'::jsonb,
 'medium','Comparaciones que resuenen con la vida real.'),

('FRAMING_UNIT_BIAS','Unit Bias','FRAMING','Reference-point',
 'Dividir precio/beneficio por unidad mínima.',
 '$0.30 por uso.','$2/clase.','$0.50 por ticket procesado.',
 'Suscripciones, consumo.',
 'Productos one-shot no fraccionables.',
 '["FRAMING_RELATIVE_COMPARISON","SALIENCE_CONCRETE_NUMBERS"]'::jsonb,
 'low','Mostrar también el total para transparencia.'),

-- =============== SALIENCE (4) ===============
('SALIENCE_CONCRETE_NUMBERS','Concrete Numbers','SALIENCE','Concreteness',
 'Usar números específicos en vez de rangos vagos.',
 'Ahorras $847 por año.','Subí tu promedio 2.3 puntos.','Reducí MTTR de 4h a 22 min.',
 'Todo el funnel — mejor que vaguedad siempre.',
 'Cuando no hay data real para el número.',
 '["SOCIAL_PROOF_SUCCESS_RATE","FRAMING_GAIN_FRAME"]'::jsonb,
 'high','Verificable y no inflado.'),

('SALIENCE_VIVID_EXAMPLES','Vivid Examples','SALIENCE','Memorability',
 'Ejemplos concretos, sensoriales, memorables.',
 'Imaginá lunes a la mañana y tu bandeja en cero.','Viernes 18h sin corregir tareas.','Demo review del CEO sin bugs abiertos.',
 'Copy de landing, cierres de pitch.',
 'Ejemplos genéricos o inverosímiles.',
 '["FRAMING_GAIN_FRAME","SALIENCE_IDENTIFIABLE_VICTIM"]'::jsonb,
 'medium','Ejemplos representativos, no extremos.'),

('SALIENCE_PEAK_END_RULE','Peak-End Rule','SALIENCE','Memorability',
 'Diseñar el clímax y el cierre memorables.',
 'Termina con el gran "aha" de ahorro.','Cierra con el diploma en mano.','Final del onboarding: deploy exitoso.',
 'Experiencia de producto y comunicación.',
 'No aplica a one-shot sin continuidad.',
 '["COMMITMENT_PROGRESS_TRACKING","SALIENCE_CONCRETE_NUMBERS"]'::jsonb,
 'low','Aplica al diseño, no al claim.'),

('SALIENCE_IDENTIFIABLE_VICTIM','Identifiable Victim','SALIENCE','Memorability',
 'Foco en una persona concreta (no estadística fría).',
 '"Lucía recuperó 10h/semana".','"Matías cambió de carrera a los 32".','"Acme bajó churn 40% con CFO Julia".',
 'Cuando hay una historia poderosa disponible.',
 'Escalar a grandes cifras — atomiza el impacto.',
 '["SOCIAL_PROOF_PEER_TESTIMONIALS","SALIENCE_VIVID_EXAMPLES"]'::jsonb,
 'medium','Con consentimiento del "victim".'),

-- =============== DEFAULTS & EASE (4) ===============
('DEFAULTS_PRE_SELECTION','Pre-Selection','DEFAULTS_EASE','Pre-selection',
 'Preseleccionar la opción recomendada por default.',
 'Plan "Recomendado" ya elegido.','Carrera recomendada marcada.','Pricing sugerido pre-tildado.',
 'Planes con diferenciales no obvios.',
 'Regulado — consentimiento explícito requerido.',
 '["SOCIAL_PROOF_WISDOM_OF_CROWDS","DEFAULTS_AUTO_ENROLLMENT"]'::jsonb,
 'medium','Siempre fácil cambiar el default.'),

('DEFAULTS_ONE_CLICK','One-Click','DEFAULTS_EASE','Friction-reduction',
 'Minimizar pasos para la conversión.',
 'Registrate en 1 click.','Inscribite con un click.','Deploy en 1 click.',
 'Productos donde cada paso pierde usuarios.',
 'Si hay que guardar data sensible sí o sí.',
 '["RECIPROCITY_FREE_TRIAL","COMMITMENT_SMALL_FIRST_STEP"]'::jsonb,
 'medium','Seguir recabando consentimiento de data.'),

('DEFAULTS_AUTO_ENROLLMENT','Auto-Enrollment','DEFAULTS_EASE','Pre-selection',
 'Inscribir automáticamente con opción de opt-out.',
 'Renovación automática anual.','Inscripción automática al curso siguiente.','Seat enterprise auto-provision.',
 'Recurrentes, fidelización.',
 'Cuando el cliente no espera recurrencia.',
 '["DEFAULTS_PRE_SELECTION","COMMITMENT_STREAK_MAINTENANCE"]'::jsonb,
 'high','Aviso previo a cobro, opt-out fácil, reglamentos.'),

('DEFAULTS_SIMPLIFIED_CHOICE','Simplified Choice','DEFAULTS_EASE','Friction-reduction',
 'Limitar opciones (3 planes vs 12).',
 '3 planes, claros.','2 modalidades: online / presencial.','Starter / Growth / Enterprise.',
 'Evitar análisis-parálisis.',
 'Productos que se venden por customización.',
 '["DEFAULTS_PRE_SELECTION","FRAMING_RELATIVE_COMPARISON"]'::jsonb,
 'low','No ocultar opciones útiles por reducirlas.'),

-- =============== CURIOSITY (4) ===============
('CURIOSITY_KNOWLEDGE_GAP','Knowledge Gap','CURIOSITY','Gap',
 'Crear brecha entre lo que el target sabe y lo que necesita saber.',
 'Lo que nadie te cuenta sobre X.','Lo que tu profesor olvidó enseñarte.','La métrica que CFOs ocultan a CEOs.',
 'Top-of-funnel, content marketing.',
 'Si el contenido no entrega el "secret".',
 '["CURIOSITY_SURPRISING_FACT","RECIPROCITY_FREE_RESOURCES"]'::jsonb,
 'medium','Cumplir la promesa — no clickbait.'),

('CURIOSITY_SURPRISING_FACT','Surprising Fact','CURIOSITY','Gap',
 'Dato contraintuitivo que engancha.',
 'El 80% tira el primer contrato.','El 67% de carreras cambian en 5 años.','50% de migraciones fracasan por política, no técnica.',
 'Leads y thought leadership.',
 'Datos fáciles de refutar.',
 '["AUTHORITY_RESEARCH_BACKED","SALIENCE_CONCRETE_NUMBERS"]'::jsonb,
 'medium','Siempre con fuente verificable.'),

('CURIOSITY_MYSTERY_BENEFIT','Mystery Benefit','CURIOSITY','Paradox',
 'Insinuar beneficio sin decirlo completo.',
 'Un beneficio que no esperás.','Un hack académico que enseñan solo los tutores.','Una feature oculta que los power-users usan.',
 'Teasing de features, lanzamientos.',
 'Si al revelar decepciona.',
 '["CURIOSITY_KNOWLEDGE_GAP","SCARCITY_EXCLUSIVE_ACCESS"]'::jsonb,
 'medium','Revelación debe valer la pena.'),

('CURIOSITY_COUNTER_INTUITIVE','Counter-Intuitive','CURIOSITY','Paradox',
 'Claim que contradice el sentido común.',
 'Dormí más, trabajá menos, rendí mejor.','Estudiá menos, aprendé más.','Automatizá menos para escalar más.',
 'Metodologías disruptivas.',
 'Si el claim no se sostiene con evidencia.',
 '["AUTHORITY_RESEARCH_BACKED","CURIOSITY_SURPRISING_FACT"]'::jsonb,
 'high','Evidencia obligatoria.'),

-- =============== STATUS & IDENTITY (5) ===============
('STATUS_EXCLUSIVITY','Exclusivity','STATUS_IDENTITY','Exclusivity',
 'No todos pueden entrar — criterios explícitos.',
 'Solo para miembros.','Admisión por test.','Solo empresas Series B+.',
 'Premium, comunidades curadas.',
 'Exclusividad performativa sin criterio real.',
 '["SCARCITY_EXCLUSIVE_ACCESS","STATUS_ELITE_GROUP"]'::jsonb,
 'high','Criterio claro y aplicado consistentemente.'),

('STATUS_ELITE_GROUP','Elite Group','STATUS_IDENTITY','Exclusivity',
 'Asociar al target con un grupo selecto.',
 'Sumate al círculo de los elegidos.','Grupo de top-performers.','Sumate al grupo de CTOs innovadores.',
 'Targets con autoimagen aspiracional.',
 'Mass-market — suena esnob.',
 '["STATUS_ASPIRATION_MODELING","STATUS_EXCLUSIVITY"]'::jsonb,
 'medium','No exclusión por criterios protegidos.'),

('STATUS_VIP_TREATMENT','VIP Treatment','STATUS_IDENTITY','Aspiration',
 'Trato diferenciado premium.',
 'Fast lane exclusivo.','Tutor personal asignado.','Customer Success Manager dedicado.',
 'Tiers premium de productos.',
 'Cuando el trato VIP es mínimamente superior.',
 '["STATUS_ELITE_GROUP","RECIPROCITY_BONUS_CONTENT"]'::jsonb,
 'medium','Cumplir la experiencia VIP efectivamente.'),

('STATUS_PREMIUM_POSITIONING','Premium Positioning','STATUS_IDENTITY','Aspiration',
 'Lenguaje, estética y precio que posicionan arriba.',
 'La experiencia más refinada.','El posgrado más selectivo.','La suite enterprise de mayor reputación.',
 'Marcas con ticket alto justificado.',
 'Productos low-cost — posicionamiento incoherente.',
 '["FRAMING_ANCHORING_HIGH","AUTHORITY_AWARDS"]'::jsonb,
 'medium','Posicionamiento debe matchear el producto real.'),

('STATUS_ASPIRATION_MODELING','Aspiration Modeling','STATUS_IDENTITY','Aspiration',
 'Mostrar al target la versión ideal de sí mismo.',
 'Sos del tipo que no se conforma.','Imaginate liderando el aula.','Imaginate siendo el CFO que resolvió la crisis.',
 'Lifestyle, educación ejecutiva, carrera.',
 'Si la aspiración no es realista para el target.',
 '["COMMITMENT_IDENTITY_ALIGNMENT","STATUS_ELITE_GROUP"]'::jsonb,
 'medium','No explotar ansiedad aspiracional.'),

-- =============== FRESH START (4) ===============
('FRESHSTART_NEW_YEAR','New Year','FRESH_START','Temporal-landmark',
 'Aprovechar el inicio de año como catalizador.',
 '2026 arrancá distinto.','Empezá el año con la carrera resuelta.','Q1 2026: migrá de una vez.',
 'Campañas de enero, resolutions.',
 'Fuera de la ventana temporal.',
 '["COMMITMENT_PUBLIC_COMMITMENT","PLANNING_IMPLEMENTATION_INTENTION"]'::jsonb,
 'medium','No forzar contextos reales.'),

('FRESHSTART_NEW_SEMESTER','New Semester','FRESH_START','Temporal-landmark',
 'Nueva cohorte/ciclo académico como reset.',
 'Semestre nuevo, hábito nuevo.','Arrancá en agosto con pie firme.','Fiscal Q2 2026: renováte.',
 'Educación y B2B con ciclos fiscales.',
 'Fuera de ciclo académico relevante.',
 '["SCARCITY_ENROLLMENT_WINDOWS","COMMITMENT_SMALL_FIRST_STEP"]'::jsonb,
 'medium','Ventana temporal real.'),

('FRESHSTART_LIFE_MILESTONE','Life Milestone','FRESH_START','Temporal-landmark',
 'Atar la decisión a un hito vital (boda, hijo, ascenso).',
 'Antes de ser padre, poné tus finanzas en orden.','Ya graduado, tu siguiente salto.','Tras el promote a VP, profesionalizá tu stack.',
 'Life-stage marketing.',
 'Sin contexto — invasivo.',
 '["LOSS_AVERSION_CAREER_STAGNATION","COMMITMENT_IDENTITY_ALIGNMENT"]'::jsonb,
 'medium','Respetar privacidad y sensibilidad.'),

('FRESHSTART_MARKET_SHIFT','Market Shift (Fresh Start)','FRESH_START','Temporal-landmark',
 'Cambio de contexto macro como excusa para empezar de cero.',
 'El mercado cambió — empezá con el pie derecho.','Reforma educativa = nuevo comienzo.','Nueva regulación: momento para reconfigurar.',
 'B2B macro-shifts.',
 'Cambios viejos o irrelevantes.',
 '["URGENCY_MARKET_SHIFT","URGENCY_BREAKING_NEWS"]'::jsonb,
 'medium','Fecha y fuente del shift claros.'),

-- =============== PRESENT BIAS (3) ===============
('PRESENT_BIAS_INSTANT_GRATIFICATION','Instant Gratification','PRESENT_BIAS','Immediacy',
 'Recompensa inmediata al registrarse/empezar.',
 'Recibí 20% off al instante.','Acceso inmediato al simulador.','Dashboard configurado en 5 min.',
 'Activación de usuarios, onboarding.',
 'Productos cuya curva de valor es larga.',
 '["URGENCY_IMMEDIATE_BENEFIT","RECIPROCITY_BONUS_CONTENT"]'::jsonb,
 'medium','No prometer gratificación que no se cumple.'),

('PRESENT_BIAS_IMMEDIATE_ACCESS','Immediate Access','PRESENT_BIAS','Immediacy',
 'Entrega/acceso el mismo día.',
 'Acceso desde hoy.','Clase disponible ya.','Sandbox listo en 60 segundos.',
 'Digital goods, SaaS self-serve.',
 'Productos físicos con logística larga.',
 '["DEFAULTS_ONE_CLICK","URGENCY_IMMEDIATE_BENEFIT"]'::jsonb,
 'low','Cumplir tiempos reales.'),

('PRESENT_BIAS_QUICK_WIN','Quick Win','PRESENT_BIAS','Immediacy',
 'Primer resultado tangible en poco tiempo.',
 'Primer resultado en 24h.','Aprendé tu primer concepto en 10 min.','Primer workflow desplegado en la 1ra semana.',
 'Curvas de adopción cortas, activación.',
 'Procesos largos sin hito temprano diseñable.',
 '["FRAMING_GAIN_FRAME","COMMITMENT_SMALL_FIRST_STEP"]'::jsonb,
 'medium','Quick win real, no maquillado.'),

-- =============== PLANNING FALLACY (3) ===============
('PLANNING_IMPLEMENTATION_INTENTION','Implementation Intention','PLANNING_FALLACY','Implementation',
 'Planificar CUÁNDO y DÓNDE se ejecuta la acción.',
 'Cada martes 18h.','Martes y jueves 20h es tu clase.','Todos los lunes 9am, deployment review.',
 'Adopción de hábitos, activación.',
 'Tareas one-off no-recurrentes.',
 '["PLANNING_IF_THEN","COMMITMENT_STREAK_MAINTENANCE"]'::jsonb,
 'low','Realismo — no agenda imposible.'),

('PLANNING_IF_THEN','If-Then Planning','PLANNING_FALLACY','Implementation',
 'Reglas condicionales que disparan la acción.',
 'Si es lunes, entonces entrenás.','Si termina clase, repasás 10 min.','Si hay alerta SEV-2, entonces runbook en 5 min.',
 'Retention, adopción.',
 'Contextos sin triggers claros.',
 '["PLANNING_IMPLEMENTATION_INTENTION","COMMITMENT_PROGRESS_TRACKING"]'::jsonb,
 'low','Reglas sostenibles.'),

('PLANNING_CONCRETE_NEXT_STEP','Concrete Next Step','PLANNING_FALLACY','Implementation',
 'Siguiente paso ultra-específico y pequeño.',
 'Click acá y empezá.','Tu próximo paso: abrí el módulo 1.','Tu próximo paso: agendá kickoff 30 min.',
 'CTAs, email de activación.',
 'Cuando el paso necesita contexto previo.',
 '["COMMITMENT_SMALL_FIRST_STEP","DEFAULTS_ONE_CLICK"]'::jsonb,
 'low','Evitar CTAs ambiguas.')

ON CONFLICT (nudge_id) DO NOTHING;

COMMIT;
